### PR TITLE
src: api improvements

### PR DESCRIPTION
**Pull request by chris-ramon**
#### Overview
- [x] Adds `SilentEchoScript.prettiyAsHTML(result: ISilentEchoValidatorResult)` implementation & test.

#### Test plan
- [x] Manual test.

### CODE REVIEW

**Comment by jkelvie** [comment]
Can you include a screenshot of the generated HTML?

**Comment by chris-ramon** [comment]
> Can you include a screenshot of the generated HTML?

Yes, there it is:

image

**Comment by jkelvie** [comment]
Looks nice, though can we add some color to it? Green text for success, red for failure?

And the overall part ("4 succeeded, 2 failed") should show as green if all succeed, red if any failed.

**Comment by chris-ramon** [comment]
> Looks nice, though can we add some color to it? Green text for success, red for failure?
> 
> And the overall part ("4 succeeded, 2 failed") should show as green if all succeed, red if any failed.

Sure thing,

image

**Pull request merged**
